// front-end/src/layout/Pagination.svelte
<script>
  import { listResponse } from "../store/list";
  import { location, push, querystring } from "svelte-spa-router";

  /**
   * @param {number} page
   */
  async function goToPage(page) {
    const searchParams = new URLSearchParams($querystring);
    searchParams.set("page", String(page));
    push(`${$location}?${searchParams.toString()}`);
  }

  const pageRange = 3;
  function getPages() {
    const pages = [];
    for (
      let i = Math.max(1, $listResponse.currentPage - pageRange);
      i <=
      Math.min($listResponse.totalPages, $listResponse.currentPage + pageRange);
      i++
    ) {
      pages.push(i);
    }
    return pages;
  }
  console.log(getPages());
</script>

{#if $listResponse.totalPages > 1}
  <nav aria-label="Page navigation example mt-2">
    <ul class="pagination justify-content-center">
      {#if $listResponse.hasPrevious}
        <li class="page-item">
          <button
            class="page-link"
            on:click={() => {
              goToPage($listResponse.currentPage - 1);
            }}>Previous</button
          >
        </li>
      {:else}
        <li class="page-item disabled">
          <button class="page-link">Previous</button>
        </li>
      {/if}

      {#if $listResponse.currentPage > pageRange + 1}
        <li class="page-item">
          <button class="page-link" on:click={() => goToPage(1)}> 1 </button>
        </li>
        {#if $listResponse.currentPage > pageRange + 2}
          <li class="page-item disabled">
            <span class="page-link">...</span>
          </li>
        {/if}
      {/if}

      {#each getPages() as page}
        <li
          class="page-item {$listResponse.currentPage === page ? 'active' : ''}"
        >
          <button class="page-link" on:click={() => goToPage(page)}>
            {page}
          </button>
        </li>
      {/each}

      {#if $listResponse.currentPage < $listResponse.totalPages - pageRange}
        {#if $listResponse.currentPage < $listResponse.totalPages - pageRange - 1}
          <li class="page-item disabled">
            <span class="page-link">...</span>
          </li>
        {/if}
        <li class="page-item">
          <button
            class="page-link"
            on:click={() => goToPage($listResponse.totalPages)}
          >
            {$listResponse.totalPages}
          </button>
        </li>
      {/if}

      {#if $listResponse.hasNext}
        <li class="page-item">
          <button
            class="page-link"
            on:click={() => {
              goToPage($listResponse.currentPage + 1);
            }}>Next</button
          >
        </li>
      {:else}
        <li class="page-item disabled">
          <button class="page-link">Next</button>
        </li>
      {/if}
    </ul>
  </nav>
{/if}

// front-end/src/layout/Pagination.tsx
import { useState } from "react";
import { PaginationProps } from "./types";
import { useSearchParams } from "react-router-dom";

export default function Pagination({
  currentPage,
  totalPages,
}: PaginationProps) {
  const [searchParams, setSearchParams] = useSearchParams();
  const [pageRange] = useState(2); // Example state, can be adjusted as needed

  if (currentPage === undefined) {
    currentPage = 0;
  }
  if (totalPages === undefined) {
    totalPages = 0;
  }

  const changePage = (currentPage: number) => {
    if (currentPage >= 1 && currentPage <= totalPages) {
      // Replace with your navigation logic (e.g., React Router's useHistory)
      const queryParams = searchParams;
      console.log(currentPage);
      queryParams.set("page", currentPage.toString());
      setSearchParams(queryParams);
      console.log(`Navigating to page ${currentPage}`);
    }
  };

  const getPages = () => {
    const pages = [];
    for (
      let i = Math.max(1, currentPage - pageRange);
      i <= Math.min(totalPages, currentPage + pageRange);
      i++
    ) {
      pages.push(i);
    }
    return pages;
  };

  if (currentPage < 1) {
    return <></>;
  }

  return (
    <nav className="d-flex justify-content-end">
      <ul className="pagination">
        <li className={`page-item ${currentPage === 1 ? "disabled" : ""}`}>
          <a
            className="page-link"
            href="#"
            aria-label="Previous"
            onClick={(e) => {
              e.preventDefault();
              changePage(currentPage - 1);
            }}
          >
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>

        {currentPage > pageRange + 1 && (
          <>
            <li className="page-item">
              <a
                className="page-link"
                href="#"
                onClick={(e) => {
                  e.preventDefault();
                  changePage(1);
                }}
              >
                1
              </a>
            </li>
            {currentPage > pageRange + 2 && (
              <li className="page-item disabled">
                <span className="page-link">...</span>
              </li>
            )}
          </>
        )}

        {getPages().map((page) => (
          <li
            key={page}
            className={`page-item ${currentPage === page ? "active" : ""}`}
          >
            <a
              className="page-link"
              href="#"
              onClick={(e) => {
                e.preventDefault();
                changePage(page);
              }}
            >
              {page}
            </a>
          </li>
        ))}

        {currentPage < totalPages - pageRange && (
          <>
            {currentPage < totalPages - pageRange - 1 && (
              <li className="page-item disabled">
                <span className="page-link">...</span>
              </li>
            )}
            <li className="page-item">
              <a
                className="page-link"
                href="#"
                onClick={(e) => {
                  e.preventDefault();
                  changePage(totalPages);
                }}
              >
                {totalPages}
              </a>
            </li>
          </>
        )}

        <li
          className={`page-item ${
            currentPage === totalPages ? "disabled" : ""
          }`}
        >
          <a
            className="page-link"
            href="#"
            aria-label="Next"
            onClick={(e) => {
              e.preventDefault();
              changePage(currentPage + 1);
            }}
          >
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      </ul>
    </nav>
  );
}
