// front-end/src/components/nav/TopNav.svelte
<script>
  import { link } from "svelte-spa-router";
  const navbar = {
    "me-auto": [
      {
        label: "Dashboard",
        url: "/",
      },
      {
        label: "Leave",
        url: "/leave",
      },
    ],
  };
</script>

<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/" use:link>HRMS APP</a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      {#each Object.entries(navbar) as [key, items] (key)}
        <ul class="navbar-nav {key} mb-2 mb-lg-0">
          {#each items as item (item.url)}
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href={item.url}
                use:link>{item.label}</a
              >
            </li>
          {/each}
        </ul>
      {/each}
    </div>
  </div>
</nav>

// front-end/src/components/Nav/TopNav.tsx
import React from "react";
import { NavLink } from "react-router-dom";
const TopNav: React.FC = () => {
  return (
    <>
      <nav className="navbar navbar-expand-lg bg-body-tertiary">
        <div className="container-fluid">
          <a className="navbar-brand" href="#">
            Navbar
          </a>
          <button
            className="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span className="navbar-toggler-icon"></span>
          </button>
          <div className="collapse navbar-collapse" id="navbarSupportedContent">
            <ul className="navbar-nav me-auto mb-2 mb-lg-0">
              <li className="nav-item">
                <NavLink
                  to="/"
                  className="nav-link active"
                  unstable_viewTransition
                >
                  Dashboard
                </NavLink>
              </li>
              <li className="nav-item">
                <NavLink
                  to="/leave"
                  className="nav-link active"
                  unstable_viewTransition
                >
                  Leave
                </NavLink>
              </li>
              <li className="nav-item dropdown">
                <a
                  className="nav-link dropdown-toggle"
                  href="#"
                  role="button"
                  data-bs-toggle="dropdown"
                  aria-expanded="false"
                >
                  Dropdown
                </a>
                <ul className="dropdown-menu">
                  <li>
                    <a className="dropdown-item" href="#">
                      Action
                    </a>
                  </li>
                  <li>
                    <a className="dropdown-item" href="#">
                      Another action
                    </a>
                  </li>
                  <li>
                    <hr className="dropdown-divider" />
                  </li>
                  <li>
                    <a className="dropdown-item" href="#">
                      Something else here
                    </a>
                  </li>
                </ul>
              </li>
              <li className="nav-item">
                <a className="nav-link disabled" aria-disabled="true">
                  Disabled
                </a>
              </li>
            </ul>
            <form className="d-flex" role="search">
              <input
                className="form-control me-2"
                type="search"
                placeholder="Search"
                aria-label="Search"
              />
              <button className="btn btn-outline-success" type="submit">
                Search
              </button>
            </form>
          </div>
        </div>
      </nav>
    </>
  );
};

export default TopNav;
